### ISSUE TITLE
Decide on level rewards

### ISSUE THREAD

**Issue by Matthew-Rickman** [binzb8294/Shadows-of-The-Dragon#11]
Do levels let you increase stats?
Do levels give skill points?
Do levels unlock new abilities?
Include skill tree?

**Comment by binzb8294** [comment]
Skill Tree is to be decided later
leveling up will be +1 to all stats and +1 in skill points
unlock new abilities with skill points 
leveling up on a multiple of 5 will give twice as many rewards
