### ISSUE TITLE
Decide on final boss

### ISSUE THREAD

**Issue by Matthew-Rickman** [binzb8294/Shadows-of-The-Dragon#12]

**Comment by binzb8294** [comment]
Dragon

**Comment by binzb8294** [comment]
![RDT_20241015_1156466330216875202168308](https://github.com/user-attachments/assets/7b1cae92-4b75-4bdd-be6c-6432fd6e2e23)
new dragon assets

**Comment by binzb8294** [comment]
use middle for boss
