### ISSUE TITLE
Music/sound effects

### ISSUE THREAD

**Issue by Matthew-Rickman** [binzb8294/Shadows-of-The-Dragon#13]

**Comment by binzb8294** [comment]
[slideshow research on topic](https://docs.google.com/presentation/d/10_MMRYa5LBMCcwQS07pVV2wE4rlMu6eA6FcaC2iaUIw/edit#slide=id.p)

**Comment by binzb8294** [comment]
[where I found the files](https://pixabay.com/sound-effects/search/cave/)

**Comment by binzb8294** [comment]
[deep-cave-159876.zip](https://github.com/user-attachments/files/17849023/deep-cave-159876.zip)
cave sound

**Comment by binzb8294** [comment]
[creepy-cave-47164.zip](https://github.com/user-attachments/files/17849058/creepy-cave-47164.zip)
possibly a cave sound for when monsters are nearby like a boss or something like that

**Comment by binzb8294** [comment]
[cave-monster-43826.zip](https://github.com/user-attachments/files/17849085/cave-monster-43826.zip)
could be the sound for the dragon right before you reach it

**Comment by binzb8294** [comment]
[dragon-breath.zip](https://github.com/user-attachments/files/17849101/dragon-breath.zip)
for fire attacks from the dragon

**Comment by binzb8294** [comment]
[player-slash.zip](https://github.com/user-attachments/files/17849137/player-slash.zip)
when player uses sword attacks

**Comment by binzb8294** [comment]
[dragon-movement.zip](https://github.com/user-attachments/files/17849205/dragon-movement.zip)
when dragon moves if it does

**Comment by binzb8294** [comment]
[small-monster-attack-195712.mp3.zip](https://github.com/user-attachments/files/17850066/small-monster-attack-195712.mp3.zip)
ghoul attack sound

**Comment by binzb8294** [comment]
[enchanted-spell-casting-229208.mp3.zip](https://github.com/user-attachments/files/17850131/enchanted-spell-casting-229208.mp3.zip)
[elemental-magic-spell-impact-incoming-228343.mp3.zip](https://github.com/user-attachments/files/17850133/elemental-magic-spell-impact-incoming-228343.mp3.zip)
cast then attack for Lich miniboss

**Comment by binzb8294** [comment]
[heavy-footsteps-walking-35722.mp3.zip](https://github.com/user-attachments/files/17850153/heavy-footsteps-walking-35722.mp3.zip)
player walking
