### ISSUE TITLE
research graphics implementation

### ISSUE THREAD

**Issue by Matthew-Rickman** [binzb8294/Shadows-of-The-Dragon#31]

**Comment by binzb8294** [comment]
[Link to Reasearch](https://docs.google.com/presentation/d/1_YDzDePsHw8eydYGjUjUxGtBqx_Dc7XYOE5Y3jzgGSk/edit?usp=sharing)

**Comment by binzb8294** [comment]
the slideshow has 3 sources of info to figure it out 
Google Gemini with code to copy from directly
a 5min video I took notes on with screenshots 
and a 20min+ video that I labeled sections on
