### ISSUE TITLE
week by week timeline

### ISSUE THREAD

**Issue by binzb8294** [binzb8294/Shadows-of-The-Dragon#38]
now to end of project

**Comment by Matthew-Rickman** [comment]
Go to slideshow issue for the link

**Comment by binzb8294** [comment]
[timeline link here](https://docs.google.com/presentation/d/1_RUBn753EvjOn1GwRFYuhFazFtHi7lnhC7NbhJzorYc/edit#slide=id.g312f24ef1ca_0_0)
