### ISSUE TITLE
Create/Find enemy designs

### ISSUE THREAD

**Issue by Matthew-Rickman** [binzb8294/Shadows-of-The-Dragon#9]

**Comment by binzb8294** [comment]
Find/create enemies from decide on basic enemies issue

**Comment by binzb8294** [comment]
Find/create designs for:
*dungeon rat
*Skeleton Soldier
*zombie
*Giant Spider
*cultist
*ghoul
*vampire spawn
*minotaur

**Comment by binzb8294** [comment]
dungeon rat switch to bat

**Comment by binzb8294** [comment]
[bat sprite link](https://www.google.com/url?sa=i&url=https%3A%2F%2Fitch.io%2Fgame-assets%2Ftag-bat&psig=AOvVaw12QJr9hVcshHHPyxsMrKcu&ust=1729877326776000&source=images&cd=vfe&opi=89978449&ved=0CBgQ3YkBahcKEwjA7ei3xaeJAxUAAAAAHQAAAAAQFg)

**Comment by binzb8294** [comment]
[skeleton soldier link](https://www.google.com/url?sa=i&url=https%3A%2F%2Fitch.io%2Fgame-assets%2Ftag-skeletons%2Ftag-sprites&psig=AOvVaw3pYB4sWsd0whoHQsH1u_Zj&ust=1729877623712000&source=images&cd=vfe&opi=89978449&ved=0CBgQ3YkBahcKEwjg6-zgxqeJAxUAAAAAHQAAAAAQBA)

**Comment by binzb8294** [comment]
[zombie link](https://www.google.com/url?sa=i&url=https%3A%2F%2Fitch.io%2Fgame-assets%2Ftag-sprites%2Ftag-zombies&psig=AOvVaw2SgU-QgS4YBzIj4FKwIZ3t&ust=1729877782201000&source=images&cd=vfe&opi=89978449&ved=0CBgQ3YkBahcKEwiAw4aKx6eJAxUAAAAAHQAAAAAQBA)

**Comment by binzb8294** [comment]
Switch giant spider to the cursed sword

**Comment by binzb8294** [comment]
[cursed sword](https://www.google.com/url?sa=i&url=https%3A%2F%2Fitch.io%2Fgame-assets%2Ftag-16x16%2Ftag-swords&psig=AOvVaw39FK_ZlVS6YKcb9nseMlRj&ust=1729878006976000&source=images&cd=vfe&opi=89978449&ved=0CBgQ3YkBahcKEwios-qLyKeJAxUAAAAAHQAAAAAQBA)

**Comment by binzb8294** [comment]
[cultist](https://www.google.com/url?sa=i&url=https%3A%2F%2Fitch.io%2Fgame-assets%2Ftag-16x16%2Ftag-cultist&psig=AOvVaw0NrF45vhMB9TOCG55vQ06R&ust=1729878096385000&source=images&cd=vfe&opi=89978449&ved=0CBgQ3YkBahcKEwjQ2LagyKeJAxUAAAAAHQAAAAAQBA)

**Comment by binzb8294** [comment]
[ghoul](https://www.google.com/url?sa=i&url=https%3A%2F%2Fitch.io%2Fgame-assets%2Ftag-ghoul&psig=AOvVaw18Qc-VWyK1jgl5GYDUncku&ust=1729878144413000&source=images&cd=vfe&opi=89978449&ved=0CBgQ3YkBahcKEwjQgY63yKeJAxUAAAAAHQAAAAAQBA)

**Comment by binzb8294** [comment]
switch vampire spawn for Lich knight

**Comment by binzb8294** [comment]
switch lich knight to lich

**Comment by binzb8294** [comment]
[Lich](https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.spriters-resource.com%2Fpc_computer%2Flostruins%2Fsheet%2F165728%2F&psig=AOvVaw18AI7CzbH5VLFwzXnEFMxf&ust=1729878607865000&source=images&cd=vfe&opi=89978449&ved=0CBgQ3YkBahcKEwiAyMuhyqeJAxUAAAAAHQAAAAAQFg)

**Comment by binzb8294** [comment]
[Minotaur](https://www.google.com/url?sa=i&url=https%3A%2F%2Fitch.io%2Fgame-assets%2Ftag-minotaur&psig=AOvVaw1aNh_g5dMVbffNJpVD1Zjf&ust=1729879998241000&source=images&cd=vfe&opi=89978449&ved=0CBgQ3YkBahcKEwigqseoz6eJAxUAAAAAHQAAAAAQBA)

**Comment by binzb8294** [comment]
use links to find sprites that work and are 16bit

**Comment by binzb8294** [comment]
![Ghoul Sprite Sheet.png](https://github.com/user-attachments/assets/ea3dcdb8-35e4-4ae7-b8f2-ad7ff8b9e517)

![PC Computer - Lost Ruins - Skeleton Lich.png](https://github.com/user-attachments/assets/9dc075e4-a386-4d0e-816c-876e20f2a18c)
